#!/bin/bash
# デプロイ準備スクリプト

echo "=========================================="
echo "  麺家弍色システム デプロイ準備"
echo "=========================================="
echo ""

# 現在のブランチを確認
current_branch=$(git branch --show-current)
echo "現在のブランチ: $current_branch"
echo ""

# 最新の状態を取得
echo "=== GitHubから最新の状態を取得 ==="
git fetch origin main
echo ""

# mainブランチの状態を確認
echo "=== mainブランチの状態 ==="
git log -n 3 --oneline main
echo ""

# デプロイチェックリスト
echo "=========================================="
echo "  デプロイチェックリスト"
echo "=========================================="
echo ""
echo "✅ コード準備:"
echo "  [✓] すべての変更をコミット済み"
echo "  [✓] genspark_ai_developer → main にマージ済み"
echo "  [✓] GitHubにプッシュ済み"
echo ""

echo "📋 次の手順:"
echo ""
echo "【1. Render（バックエンド）のデプロイ】"
echo "  1-1. https://dashboard.render.com にアクセス"
echo "  1-2. 「New +」→「Web Service」をクリック"
echo "  1-3. GitHubリポジトリを選択:"
echo "       - kazunarihonda83-jpg/menya-nishiki-system-cloud"
echo "       - Branch: main"
echo ""
echo "  1-4. サービス設定:"
echo "       Name: menya-nishiki-backend"
echo "       Region: Singapore"
echo "       Build Command: npm install"
echo "       Start Command: node server/index.js"
echo ""
echo "  1-5. 環境変数を設定:"
echo "       NODE_ENV=production"
echo "       PORT=5003"
echo "       JWT_SECRET=[ランダム文字列]"
echo "       SERVE_FRONTEND=false"
echo ""
echo "  1-6. ディスクを追加:"
echo "       Name: sqlite-data"
echo "       Mount Path: /data"
echo "       Size: 1 GB"
echo ""
echo "  1-7. 「Create Web Service」をクリック"
echo ""
echo "  1-8. デプロイ完了後、URLをメモ:"
echo "       例: https://menya-nishiki-backend.onrender.com"
echo ""
echo "  1-9. Render Shellでマイグレーション実行:"
echo "       npm run migrate"
echo ""

echo "【2. 環境変数の更新】"
echo "  2-1. .env.production を編集:"
echo "       VITE_API_URL=https://[RenderのURL]/api"
echo ""
echo "  2-2. 変更をコミット＆プッシュ:"
echo "       git add .env.production"
echo "       git commit -m 'chore: Render URL を設定'"
echo "       git push origin main"
echo ""

echo "【3. Vercel（フロントエンド）のデプロイ】"
echo "  3-1. https://vercel.com にアクセス"
echo "  3-2. 「Add New...」→「Project」をクリック"
echo "  3-3. GitHubリポジトリを選択:"
echo "       - kazunarihonda83-jpg/menya-nishiki-system-cloud"
echo ""
echo "  3-4. プロジェクト設定:"
echo "       Project Name: menya-nishiki-frontend"
echo "       Framework: Vite"
echo "       Build Command: npm run build"
echo "       Output Directory: dist"
echo ""
echo "  3-5. 環境変数を設定:"
echo "       VITE_API_URL=https://[RenderのURL]/api"
echo ""
echo "  3-6. 「Deploy」をクリック"
echo ""
echo "  3-7. デプロイ完了後、URLをメモ:"
echo "       例: https://menya-nishiki-frontend.vercel.app"
echo ""

echo "【4. 動作確認】"
echo "  4-1. バックエンドヘルスチェック:"
echo "       curl https://[RenderのURL]/api/health"
echo ""
echo "  4-2. フロントエンドにアクセス:"
echo "       https://[VercelのURL]"
echo ""
echo "  4-3. ログイン:"
echo "       ユーザー名: 麺家弍色"
echo "       パスワード: admin123"
echo ""
echo "  4-4. 各画面を確認:"
echo "       - ホーム（すべて¥0）"
echo "       - 損益計算書（すべて¥0）"
echo "       - 受注取引一覧（データなし）"
echo ""

echo "=========================================="
echo "  詳細は DEPLOYMENT_GUIDE.md を参照"
echo "=========================================="
echo ""
echo "準備完了！デプロイを開始してください。"
echo ""
